services:
  # Production build
  app:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - portfolio-app:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: portfolio-app:latest
    container_name: portfolio-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?connect_timeout=10&sslmode=prefer
    networks:
      - portfolio-network

  # Development build with hot reload
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      cache_from:
        - portfolio-app-dev:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: portfolio-app-dev:latest
    container_name: portfolio-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?connect_timeout=10&sslmode=prefer
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

